server:
  port: 8081
  servlet:
    context-path: /managementClient

spring:
  application:
    name: spring-managementClient
    
service:
    base:
        url: http://localhost:8083/springDataDemo/
    name: feignUserService    
    

feign:  client:    config:      default:
        read-timeout: 1500
        connect-timeout: 1500    